### ISSUE TITLE
Outputs SRM when input is SRM

### ISSUE THREAD

**Issue by Deozaan** [drehren/ra_mp64_srm_convert#6]
I'm using the Steam version of RetroArch with the Mupen64Plus-Next core. The SRM files it outputs are not the standard 290 kB, but vary in size from around 200 bytes to about 20 kB, depending on the game. I assumed this was a compact/trimmed save with extra padding removed, but it turns out that I had enabled SaveRAM compression in the settings, resulting in these small filesizes.

In any case, before I learned of the small filesize issue, I had some problems when trying to use my saves with other utilities, such as https://github.com/Ninjiteu/N64SaveConverter and https://github.com/MaikelChan/BKSaveEditor.

I came across ra_mp64_srm_convert and attempted to split my SRM file using the command `.\ra_mp64_srm_convert.exe '.\Banjo-Kazooie (USA).srm'` and I got an error saying it was trying to overwrite `Banjo-Kazooie (USA).srm`. The documentation leads me to believe that it should automatically detect that the file is an SRM file and attempt to split it into EEP, MPK, and SRA files.

If I explicitly use the `-s` command to tell it to split, then I get an error saying that it has an invalid file size.

If, on the other hand, I use the `-o` command to tell it to overwrite, then it outputs a 290 kB SRM file, which after some testing I've come to the conclusion isn't properly formatted and doesn't work with the other utilities mentioned. However, ra_mp64_srm_convert will happily "split" it without complaint. But I think the output files contain just junk data. Garbage in, garbage out.

The point of this issue is that the utility should detect that the input file is an SRM file and automatically attempt to split it, which in my case should have given me an invalid file size error instead of leading me to believe that it was trying to convert it to a proper 290 kB file.

**Comment by drehren** [comment]
Hi, the issue is that you need your SRM file to be 290kB, otherwise the app will fail to detect/process it. 
To make the SRM an 290kB file, you need to disable the SaveRAM compression and then play your game again (and possibly save) for it to be recreated. 
As said before, the utility does detect the SRM, when it is a file of 290kB in size, because it can only process it in its uncompressed form.

And, after a quick glance to the README, it does not explicitly state that it can only handle 290kB (uncompressed) SRM files. So I'll amend that for now.
